### ISSUE TITLE
Port to 1.19.3

### ISSUE THREAD

**Issue by stantios** [naritanara/vanity-splash-text#5]
I was wondering if there could be a port to 1.19.3. I really like this mod and it's concept of giving credits for mods in splash texts

**Comment by naritanara** [comment]
I will check compatibility and update the mod if necessary in a few hours. I just forgot about this, thank you!

**Comment by naritanara** [comment]
I checked everything and the current version of the mod works fine in 1.19.3. The mod should now be marked as available for 1.19.3 both in Modrinth and Curseforge.
